// Generated by build.rs into src/generated_bindings.rs
include!("generated_bindings.rs");

// Hand-written ZBytes serialization JNI. Java-specific (walks reflect.Type,
// builds java.util collections), so it lives here rather than in the
// language-agnostic zenoh-flat. Throws io.zenoh.jni.JniBindingError via the
// generated `throw_JniBindingError`.
#[cfg(feature = "zenoh-ext")]
mod zbytes;
