// The included JNI surface is machine-generated and intentionally favors
// uniform templates over hand-written Clippy idioms. Keep warnings strict for
// every other lint while acknowledging the generator's known patterns.
#![allow(
    clippy::blocks_in_conditions,
    clippy::clone_on_copy,
    clippy::extra_unused_lifetimes,
    clippy::let_unit_value,
    clippy::missing_safety_doc,
    clippy::needless_borrows_for_generic_args,
    clippy::unnecessary_map_on_constructor,
    clippy::unused_unit,
    clippy::useless_conversion
)]

// Generated by build.rs into src/generated_bindings.rs
include!("generated_bindings.rs");

/// Binding policy behind the `field!("handle")` leaf of the Encoding output
/// expansion (see build.rs): a received encoding carries a native handle
/// only when it has a schema. A schema-less (predefined) encoding re-sends
/// through the `(id, schema)` value arm for free — its id rides inside the
/// send call — so materializing a handle (clone + Box + JVM wrapper + GC
/// Cleaner registration, per message) would buy nothing.
pub(crate) fn encoding_if_schema(e: &zenoh_flat::Encoding) -> Option<&zenoh_flat::Encoding> {
    e.schema().is_some().then_some(e)
}

// Hand-written ZBytes serialization JNI. Java-specific (walks reflect.Type,
// builds java.util collections), so it lives here rather than in the
// language-agnostic zenoh-flat. Throws io.zenoh.jni.JniBindingError via the
// generated `throw_JniBindingError`.
#[cfg(feature = "zenoh-ext")]
mod zbytes;
